@extends('userlayout.app')
@section('title','Blog - Nova Mobility')
@push('styles')<style>body{background:#f3f4f6}.hero{background:#073b63;color:#fff;padding:70px 0 110px;margin:0;border-radius:0;height:auto}.eyebrow,.tag{display:inline-block;background:#8ec5f3;color:#083a5a;padding:7px 13px;border-radius:999px;font-weight:700;font-size:12px;text-transform:uppercase}.hero h1{font-size:58px;max-width:760px;margin:18px 0}.hero p{font-size:18px;max-width:720px}.featured{margin-top:-64px;padding-bottom:60px}.featured-card{position:relative;border-radius:28px;overflow:hidden;min-height:500px;background:#073b63}.featured-card>img{width:100%;height:500px;object-fit:cover}.featured-overlay{position:absolute;inset:0;background:linear-gradient(0deg,rgba(2,27,45,.85),transparent 70%);display:flex;align-items:end}.featured-content{padding:42px;color:#fff;max-width:820px}.featured-content h2{font-size:42px;line-height:1.12;margin:16px 0}.featured-content p{color:#d7e7f5;margin-bottom:18px}.featured-link,.read{color:#0b4b73;font-weight:700}.featured-link{color:#fff}.more{padding:20px 0 80px}.section-head h2{font-size:48px;color:#0b4b73}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:26px;margin-top:28px}.card{background:#fff;border-radius:22px;overflow:hidden;border:1px solid #e5e7eb;box-shadow:0 10px 24px rgba(0,0,0,.05)}.card img{width:100%;height:190px;object-fit:cover}.card-body{padding:22px}.card-meta{font-size:13px;color:#6b7280;font-weight:700;text-transform:uppercase}.card h3{color:#0b4b73;font-size:24px;margin:10px 0}.card p{color:#4b5563;margin-bottom:14px}.newsletter{padding:20px 0 80px}.newsletter-box{background:#073b63;color:#fff;border-radius:30px;padding:52px;display:grid;grid-template-columns:1.1fr .9fr;gap:32px}.subscribe{display:flex;gap:14px;align-items:center}.subscribe input{flex:1;padding:16px;border-radius:14px;border:1px solid #ffffff33;background:#ffffff15;color:#fff}.subscribe button{padding:16px 26px;border:0;border-radius:14px;background:#8ec5f3;font-weight:700;color:#083a5a}@media(max-width:992px){.grid,.newsletter-box{grid-template-columns:1fr}.hero h1{font-size:44px}}@media(max-width:576px){.hero h1{font-size:34px}.featured-content{padding:24px}.featured-content h2{font-size:26px}.subscribe{flex-direction:column}.subscribe>*{width:100%}}</style>@endpush
@section('content')
<section class="hero"><div class="container"><span class="eyebrow">Nova Insights</span><h1>The future of premium mobility in Myanmar.</h1><p>Discover how Nova Mobility is redefining intercity travel through sustainable technology, executive comfort, and innovative routes across the Golden Land.</p></div></section>
@if($hero)<section class="featured"><div class="container"><article class="featured-card"><img src="{{ asset('storage/'.$hero->banner_image) }}" alt="{{ $hero->title }}"><div class="featured-overlay"><div class="featured-content"><span class="tag">Featured</span><p>{{ $hero->published_at?->format('F j, Y') }}</p><h2>{{ $hero->title }}</h2><p>{{ $hero->short_description }}</p><a href="{{ route('blog.show',$hero) }}" class="featured-link">Read the full story →</a></div></div></article></div></section>@endif
<section class="more"><div class="container"><div class="section-head"><h2>More stories</h2><p>Ideas, updates, and travel inspiration from Nova.</p></div><div class="grid">@foreach($blogs as $blog)<article class="card"><img src="{{ asset('storage/'.$blog->featured_image) }}" alt="{{ $blog->title }}"><div class="card-body"><div class="card-meta">{{ $blog->category }} · {{ $blog->published_at?->format('M j, Y') }} · {{ $blog->reading_time }} min read</div><h3>{{ $blog->title }}</h3><p>{{ $blog->short_description }}</p><a class="read" href="{{ route('blog.show',$blog) }}">Read More →</a></div></article>@endforeach</div><div class="mt-8">{{ $blogs->links() }}</div></div></section>
<section class="newsletter"><div class="container"><div class="newsletter-box"><div><h3>Stay in the know</h3><p>Get Nova stories, route updates, and travel inspiration delivered to your inbox.</p></div><div><form method="POST" action="{{ route('newsletter.subscribe') }}" class="subscribe">@csrf<input name="email" type="email" placeholder="Your email address" required><button>Subscribe</button></form></div></div></div></section>
@endsection
