@extends('userlayout.app')

@section('title', 'Support - Nova Mobility')

@push('styles')
<style>
    body{background:#f3f4f6;color:#1f2937}.logo span{color:#53a7db}nav a{color:#4b5563}.hero{background:linear-gradient(135deg,#073b63,#094776,#357cb1);color:#fff;padding:90px 0;text-align:center;margin:0;border-radius:0;height:auto}.hero h1{font-size:72px;font-weight:800;margin-bottom:18px}.hero p{max-width:720px;margin:0 auto 40px;color:#d7e7f5;font-size:20px}.search-box{max-width:620px;margin:0 auto;display:flex;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 12px 30px rgba(0,0,0,.18)}.search-box input{flex:1;border:none;padding:18px 22px;font-size:16px;outline:none}.search-box button{width:70px;border:none;background:#0b4b73;color:#fff;font-size:22px;cursor:pointer}
    .support-cards{padding:70px 0 30px}.card-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:28px}.card{background:#fff;border-radius:22px;padding:36px;box-shadow:0 12px 32px rgba(0,0,0,.06);text-align:center;border:1px solid #e5e7eb}.icon{width:72px;height:72px;border-radius:50%;background:#e8f1fa;color:#0b4b73;display:flex;align-items:center;justify-content:center;font-size:32px;margin:0 auto 20px}.card h3{color:#0b4b73;font-size:34px;margin-bottom:14px}.card p{color:#6b7280;margin-bottom:22px;font-size:16px}.support-btn{display:block;padding:14px 18px;border-radius:12px;margin-bottom:12px;font-weight:600}.viber{background:#efeafe;color:#4f46e5}.whatsapp{background:#e8f8ef;color:#047857}.email{color:#0b4b73;font-weight:700;font-size:18px}.address{color:#374151;font-weight:500;margin:18px 0 22px}.map-box{background:#eef2f7;border-radius:16px;height:140px;display:flex;align-items:center;justify-content:center;color:#6b7280;font-weight:600}.map-btn{background:#fff;color:#0b4b73;padding:12px 20px;border-radius:999px;font-weight:700;box-shadow:0 6px 16px rgba(0,0,0,.08)}
    .faq{background:#eef2f5;padding:80px 0;position:relative;overflow:hidden}.faq::after{content:"";position:absolute;top:-120px;right:-140px;width:420px;height:900px;background:rgba(255,255,255,.4);transform:rotate(12deg);border-radius:120px}.faq .container{position:relative;z-index:1;max-width:900px}.faq h2{text-align:center;color:#0b4b73;font-size:60px;margin-bottom:40px}.faq-section{margin-bottom:34px}.faq-section h3{color:#0b4b73;font-size:28px;margin-bottom:18px;display:flex;align-items:center;gap:10px}details{background:#fff;border-radius:16px;margin-bottom:16px;border:1px solid #e5e7eb;overflow:hidden;box-shadow:0 6px 18px rgba(0,0,0,.04)}summary{list-style:none;cursor:pointer;padding:20px 22px;font-weight:600;color:#0b4b73;position:relative}summary::-webkit-details-marker{display:none}summary::after{content:"+";position:absolute;right:22px;top:20px;font-size:24px;color:#6b7280}details[open] summary::after{content:"−"}details p{padding:0 22px 22px;color:#6b7280}.agent{text-align:center;margin-top:34px}.agent p{color:#6b7280;margin-bottom:18px}.agent-btn{display:inline-block;background:#0b4b73;color:#fff;padding:16px 34px;border-radius:12px;font-weight:700;transition:.3s}.agent-btn:hover{background:#083a5a}footer h3{font-size:36px}footer p,footer li,.footer-bottom{color:#c8d6e4}
    @media(max-width:992px){.card-grid{grid-template-columns:1fr}.hero h1{font-size:48px}.faq h2{font-size:40px}.card h3{font-size:28px}}@media(max-width:576px){.hero{padding:70px 0}.hero h1{font-size:38px}.hero p{font-size:18px}.search-box{flex-direction:column}.search-box button{width:100%;padding:14px 0}.faq h2{font-size:32px}}
</style>
@endpush
    
@section('content')
    <section class="hero"><div class="container"><h1>Help Center</h1><p>We're here to ensure your journey is seamless. Find answers or reach out to our dedicated support team.</p><form method="GET" action="{{ route('support') }}" class="search-box"><input name="search" value="{{ $search }}" type="search" placeholder="How can we help you today?" /><button type="submit" aria-label="Search FAQs">🔍</button></form></div></section>
    <section class="support-cards"><div class="container card-grid"><div class="card"><div class="icon">💬</div><h3>Live Support</h3><p>Connect with us instantly via Viber or WhatsApp for real-time assistance.</p><a href="{{ route('support') }}#contact" class="support-btn viber">📱 Viber Support</a><a href="{{ route('support') }}#contact" class="support-btn whatsapp">📞 WhatsApp Support</a></div><div class="card"><div class="icon">✉️</div><h3>Email Inquiry</h3><p>Prefer writing? Our team typically responds within 2 business hours.</p><a href="mailto:support@novamobility.com" class="email">support@novamobility.com</a></div><div class="card" id="contact"><div class="icon">📍</div><h3>Main Hub</h3><p>Visit our flagship terminal for ticketing and premium lounge services.</p><div class="address">No. 124, Pyay Road,<br>Mayangone Township, Yangon.</div><div class="map-box"><a href="{{ route('support') }}#contact" class="map-btn">View on Map</a></div></div></div></section>
    <section class="faq"><div class="container"><h2>Frequently Asked Questions</h2>
        @forelse ($faqs->groupBy('category') as $category => $categoryFaqs)
            <div class="faq-section"><h3>{{ $category === 'Billing' ? '💳' : ($category === 'Technical' ? '🚌' : '🛡️') }} {{ $category }}</h3>@foreach ($categoryFaqs as $faq)<details><summary>{{ $faq->question }}</summary><p>{{ $faq->answer }}</p></details>@endforeach</div>
        @empty
            <div class="faq-section"><h3>No FAQs found</h3></div>
        @endforelse
        <div class="agent"><p>Can't find what you're looking for?</p><a href="{{ route('support') }}#contact" class="agent-btn">Talk to an Agent</a></div></div></section>
@endsection
